name: nowplaying_obs
description: Application for embedding currently playing song in OBS (or any other streaming software that supports window capture and chroma key)

publish_to: 'none'

version: 1.1.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  http: ^0.13.3
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-Regular.ttf
  assets:
    - assets/icon.png